name = "GeoStatsViz"
uuid = "36492b79-4a51-4dff-89b6-31e03c9a81c2"
authors = ["JÃºlio Hoffimann <julio.hoffimann@gmail.com> and contributors"]
version = "0.1.4"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
GeoStatsBase = "323cb8eb-fbf6-51c0-afd0-f8fba70507b2"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MeshViz = "9ecf9c4f-6e5a-4b5e-83ae-06f2c7a661d8"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Variography = "04a0146e-e6df-5636-8d7f-62fa9eb0b20c"

[compat]
Distances = "0.10"
GeoStatsBase = "0.29"
Makie = "0.17, 0.18, 0.19"
MeshViz = "0.6"
Meshes = "0.26"
Reexport = "1.2"
Variography = "0.15"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
